#+HUGO_BASE_DIR: hugo
#+HUGO_WEIGHT: auto
#+OPTIONS: broken-links:mark

* Licenses
:PROPERTIES:
:EXPORT_HUGO_SECTION: license
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :hidden true
:END:
This software, and the contents of [[https://blog.rymcg.tech][blog.rymcg.tech]], are dual-licensed
under the [[https://creativecommons.org/licenses/by/4.0/][Creative Commons Attribution 4.0 License]], and the MIT
license. You may use either license at your sole discretion.

For example, you may want to choose [[https://creativecommons.org/licenses/by/4.0/][CC-by]] in order to copy an article
or section of this project to another blog or website, while [[https://github.com/enigmacurry/rymcg.tech/fork][forking
this project]] might be more suitable with the terms of the MIT license.


#+BEGIN_SRC txt :tangle LICENSE.txt
This software is dual licensed: MIT and Creative Commons Attribution 4.0.
Use either license at your discretion:

https://creativecommons.org/licenses/by/4.0/

----------------------------------------------------------------------

Copyright (c) 2017 EnigmaCurry - http://blog.rymcg.tech

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#+END_SRC

The theme files distributed with the static HTML are licensed MIT. 

(If you use a different theme, you can remove this notice:)

#+BEGIN_QUOTE
Copyright (c) 2014 Grav 
Copyright (c) 2016 MATHIEU CORNIC 
Copyright (c) 2017 Valere JEANTET

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#+END_QUOTE
